CREATE DATABASE ROMAN;
GO

USE ROMAN;
GO

CREATE TABLE professor (
	idProfessor SMALLINT PRIMARY KEY IDENTITY,
	email VARCHAR(50) UNIQUE NOT NULL,
	senha VARCHAR(20) NOT NULL,
	nomeProfessor VARCHAR(50) NOT NULL
);
GO

CREATE TABLE tema (
	idTema SMALLINT PRIMARY KEY IDENTITY,
	tituloTema VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE projeto (
	idProjeto SMALLINT PRIMARY KEY IDENTITY,
	idProfessor SMALLINT FOREIGN KEY REFERENCES professor(idProfessor) NOT NULL,
	idTema SMALLINT FOREIGN KEY REFERENCES tema(idTema) NOT NULL,
	tituloProjeto VARCHAR(50) NOT NULL,
	descricao VARCHAR(200) NOT NULL
);
GO



